name: colbert1
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip=23.3
  - pytorch=2.1.1
  - torchvision=0.16.1
  - pip:
    - mlflow
    - tensorboard
    - tqdm
    - transformers==4.36.1
    - ujson
